apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-retain
  namespace: nfs-provisioner
provisioner: nfs-retain
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"

